# Generated by Django 4.2.2 on 2023-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_device_plans_resolution_plans_video_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='active_screens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
