# Generated by Django 4.2.2 on 2023-08-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_plans_active_screens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCache',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
